### ISSUE TITLE
clearTimeout doesn't work

### ISSUE THREAD

**Issue by paulmckee** [JamesMGreene/node-safetimeout#1]
I'm using safetimeout with Node.js 8.2.1 and I find that clearTimeout doesn't work.

**To repro:**
```javascript
  const safe = require('safetimeout');
  safe.clearTimeout(safe.setTimeout(() => console.log("Timed out"), 3000));
```

**Expected result:** "Timed out" is not printed

**Actual result:** "Timed out" is printed after 3 seconds, even though the timeout should have been cleared.

I think this is due to `safeClear` requiring, at line 71 in index.js, that the typeof the ID returned from the platform's `setTimeout` is `string` before calling `clearTimeout`.  `setTimeout` on Node.js actually returns a Timeout object.

**Comment by JamesMGreene** [comment]
Hmm.  Well, I guess _that_ definitely gives me a reason to write some unit tests for the less than max-Int32 use cases.

Thanks for bringing it to my attention.

**Comment by JamesMGreene** [comment]
After wasting a few hours redesigning this library and deciding to rename it, I found that the name I wanted was already taken by a package that has already done a better job of all this than my old module here. 😕 

And so, I recommend you switch over to using that: https://www.npmjs.com/package/safe-timers

**Comment by JamesMGreene** [comment]
P.S. `safe-timers` does not have 100% API parity, so watch out for that (or encourage them to add it [over here](https://github.com/Wizcorp/safe-timers/issues/4)).

**Comment by JamesMGreene** [comment]
I am going to close this out as I am deprecating this module in favor of the aforementioned `safe-timers` module. :confused:
